import { NextResponse } from 'next/server';

const heroes = [
  {
    id: 'xiang_yu',
    name: '项羽',
    title: '西楚霸王',
    rarity: 'SSR',
    faction: '楚',
    role: '战士',
    element: 'Fire',
    stats: { atk: 95, def: 88, hp: 90, spd: 70, crit: 85 },
    keywords: ['霸气', '重甲', '霸王枪', '战场背景'],
    sdPrompt: 'Chinese ancient warrior general Xiang Yu, Hegemon-King of Western Chu, imposing figure wearing heavy dark iron armor with bronze dragon motifs, holding a massive halberd spear, flowing red cape, battlefield background with burning flags, dramatic lighting, warring states period, epic fantasy art style, highly detailed, 8k quality, cinematic composition, dark moody atmosphere',
    portrait: '/heroes/xiang_yu.png',
    skills: [
      { id: 'xiangyu_1', name: '霸王击', type: 'AOE', element: 'Fire', damage: 180, cooldown: 8, desc: '项羽挥舞霸王枪，对周围敌人造成范围伤害，附带击退效果', particles: 'fire_explosion, shockwave', sound: 'heavy_swing, explosion', animation: 'skill_heavy_strike' },
      { id: 'xiangyu_2', name: '破釜沉舟', type: 'Buff', element: 'Fire', damage: 0, cooldown: 20, desc: '自毁退路，大幅提升攻击力和防御力，持续10秒', particles: 'fire_aura, rising_flames', sound: 'war_cry, buff_activate', animation: 'skill_buff_roar' },
      { id: 'xiangyu_3', name: '四面楚歌', type: 'Control', element: 'Dark', damage: 120, cooldown: 15, desc: '播放四面楚歌，使范围内敌人陷入眩晕状态3秒', particles: 'dark_mist, sound_waves', sound: 'eerie_music, crowd_chant', animation: 'skill_chant' },
    ],
  },
  {
    id: 'liu_bang',
    name: '刘邦',
    title: '汉高祖',
    rarity: 'SSR',
    faction: '汉',
    role: '统帅',
    element: 'Light',
    stats: { atk: 70, def: 82, hp: 85, spd: 75, crit: 65 },
    keywords: ['帝王之气', '龙袍', '金光', '宫殿'],
    sdPrompt: 'Chinese ancient emperor Liu Bang, founder of Han Dynasty, regal noble figure wearing golden dragon robe with jade accessories, seated on ornate throne, divine imperial aura, warm golden light emanating, ancient Chinese palace interior, warring states period art style, majestic composition, 8k quality',
    portrait: '/heroes/liu_bang.png',
    skills: [
      { id: 'liubang_1', name: '天命所归', type: 'Buff', element: 'Light', damage: 0, cooldown: 25, desc: '激活天命光环，全体友军攻击力和防御力提升30%，持续15秒', particles: 'golden_aura, divine_light', sound: 'divine_bell, choir', animation: 'skill_imperial_decree' },
      { id: 'liubang_2', name: '知人善任', type: 'Buff', element: 'Light', damage: 0, cooldown: 18, desc: '指定一名友方武将，使其技能冷却时间减半，持续8秒', particles: 'light_beam, contract_seal', sound: 'scroll_unfurl, seal_stamp', animation: 'skill_point' },
      { id: 'liubang_3', name: '约法三章', type: 'Control', element: 'Light', damage: 100, cooldown: 20, desc: '释放三章法令，使敌方全体减速50%持续5秒', particles: 'golden_chains, law_runes', sound: 'gavel_strike, chains', animation: 'skill_slam' },
    ],
  },
  {
    id: 'han_xin',
    name: '韩信',
    title: '兵仙',
    rarity: 'SSR',
    faction: '汉',
    role: '策略',
    element: 'Thunder',
    stats: { atk: 90, def: 75, hp: 78, spd: 92, crit: 88 },
    keywords: ['冷峻', '银甲', '兵书', '蓝光'],
    sdPrompt: 'Chinese ancient military genius Han Xin, the God of War, young handsome general in sleek dark armor with silver accents, holding a strategic bamboo scroll, standing on a cliff overlooking vast army formations, cool blue energy aura, warring states period, strategic mastermind, epic fantasy art, highly detailed face, 8k quality, cinematic lighting',
    portrait: '/heroes/han_xin.png',
    skills: [
      { id: 'hanxin_1', name: '背水一战', type: 'AOE', element: 'Thunder', damage: 200, cooldown: 12, desc: '背水列阵，释放雷电风暴，对前方扇形区域造成毁灭性伤害', particles: 'lightning_storm, electric_arcs', sound: 'thunder_clap, lightning_strike', animation: 'skill_thunder_slash' },
      { id: 'hanxin_2', name: '暗度陈仓', type: 'SingleBurst', element: 'Thunder', damage: 350, cooldown: 15, desc: '瞬间传送至敌方后排，对单体造成巨额伤害并附带眩晕', particles: 'thunder_step, shadow_dash', sound: 'teleport, critical_hit', animation: 'skill_shadow_strike' },
      { id: 'hanxin_3', name: '十面埋伏', type: 'Control', element: 'Dark', damage: 150, cooldown: 18, desc: '布下十面埋伏之阵，使敌方全体被困4秒并持续受到伤害', particles: 'shadow_trap, chain_net', sound: 'trap_close, ambient_dread', animation: 'skill_trap' },
    ],
  },
  {
    id: 'jing_ke',
    name: '荆轲',
    title: '刺客',
    rarity: 'SR',
    faction: '群',
    role: '刺客',
    element: 'Dark',
    stats: { atk: 92, def: 55, hp: 65, spd: 98, crit: 95 },
    keywords: ['刺客', '匕首', '暗夜', '匕首藏图'],
    sdPrompt: 'Chinese ancient assassin Jing Ke, legendary assassin of warring states, lean muscular figure in dark leather assassin garb, carrying a poisoned dagger concealed in a map scroll, rooftop scene at night, moonlight shadows, mysterious and dangerous aura, warring states period, dark fantasy art, dramatic lighting, 8k quality',
    portrait: '/heroes/jing_ke.png',
    skills: [
      { id: 'jingke_1', name: '图穷匕见', type: 'SingleBurst', element: 'Dark', damage: 400, cooldown: 10, desc: '展开地图，匕首突刺，对单体造成极高暴击伤害', particles: 'shadow_blade, poison_splash', sound: 'blade_draw, critical_hit', animation: 'skill_assassinate' },
      { id: 'jingke_2', name: '易水寒', type: 'Control', element: 'Ice', damage: 80, cooldown: 12, desc: '散发易水寒气，冰冻目标3秒并造成持续伤害', particles: 'ice_blade, frost_aura', sound: 'ice_freeze, wind_howl', animation: 'skill_ice_strike' },
      { id: 'jingke_3', name: '燕赵悲歌', type: 'Buff', element: 'Dark', damage: 0, cooldown: 22, desc: '激发悲壮战意，自身暴击率和暴击伤害大幅提升12秒', particles: 'dark_flames, resolve_aura', sound: 'war_chant, resolve', animation: 'skill_resolve' },
    ],
  },
  {
    id: 'bai_qi',
    name: '白起',
    title: '战神',
    rarity: 'SSR',
    faction: '秦',
    role: '战士',
    element: 'Fire',
    stats: { atk: 98, def: 90, hp: 95, spd: 60, crit: 80 },
    keywords: ['嗜血', '重斧', '骷髅铠', '血色光环'],
    sdPrompt: 'Chinese ancient god of war Bai Qi, the Butcher General of Qin state, intimidating tall figure in blood-red heavy armor with skull helmet decorations, wielding a massive battle axe dripping with dark energy, standing among fallen enemies on a battlefield, dark crimson aura, fearsome presence, warring states period, dark fantasy art, 8k quality',
    portrait: '/heroes/bai_qi.png',
    skills: [
      { id: 'baiqi_1', name: '长平之战', type: 'AOE', element: 'Fire', damage: 220, cooldown: 14, desc: '重现长平之战，释放地狱火焰，对大范围敌人造成毁灭伤害', particles: 'hellfire, blood_explosion, bone_shards', sound: 'massive_explosion, war_drums', animation: 'skill_slam_ground' },
      { id: 'baiqi_2', name: '杀神降临', type: 'Buff', element: 'Dark', damage: 0, cooldown: 25, desc: '化身杀神，攻击力提升50%且每次攻击回复生命值，持续12秒', particles: 'blood_aura, skull_spirits', sound: 'demonic_roar, heartbeat', animation: 'skill_transform' },
      { id: 'baiqi_3', name: '人屠', type: 'SingleBurst', element: 'Fire', damage: 380, cooldown: 16, desc: '挥动巨斧，对单体造成巨额伤害，若目标生命值低于30%则直接斩杀', particles: 'execution_blade, blood_geyser', sound: 'axe_slash, execution', animation: 'skill_execute' },
    ],
  },
  {
    id: 'zhang_liang',
    name: '张良',
    title: '谋圣',
    rarity: 'SR',
    faction: '汉',
    role: '策略',
    element: 'Wind',
    stats: { atk: 72, def: 60, hp: 70, spd: 88, crit: 75 },
    keywords: ['仙风道骨', '羽扇', '全息兵法', '水墨'],
    sdPrompt: 'Chinese ancient strategist Zhang Liang, brilliant scholar strategist of Han Dynasty, elegant figure in flowing white and blue scholar robes, holding a jade fan, surrounded by floating holographic battle strategy maps and ancient Chinese calligraphy symbols, divine wisdom aura, serene mountain temple background, warring states period, mystical fantasy art, 8k quality, soft ethereal lighting',
    portrait: '/heroes/zhang_liang.png',
    skills: [
      { id: 'zhangliang_1', name: '运筹帷幄', type: 'Control', element: 'Wind', damage: 130, cooldown: 15, desc: '释放全息兵法阵，减速并沉默范围内敌人4秒', particles: 'ink_swirl, strategy_map, wind_vortex', sound: 'fan_wave, whisper', animation: 'skill_fan_wave' },
      { id: 'zhangliang_2', name: '明修栈道', type: 'Buff', element: 'Wind', damage: 0, cooldown: 20, desc: '为全体友军创建幻影分身，吸引敌方攻击8秒', particles: 'wind_clone, illusion', sound: 'wind_gust, magic_create', animation: 'skill_create_clone' },
      { id: 'zhangliang_3', name: '暗度陈仓', type: 'SingleBurst', element: 'Wind', damage: 280, cooldown: 12, desc: '操控风向，对指定敌人发射穿透性风刃', particles: 'wind_blade, air_slash', sound: 'wind_slash, pierce', animation: 'skill_wind_strike' },
    ],
  },
];

export async function GET() {
  return NextResponse.json({ heroes, total: heroes.length });
}
